version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: 12
    commands:
      # Install sam cli
      - pip3 install --upgrade aws-sam-cli
      - sam --version
      - cd hello-world
      - npm install

  pre_build:
    commands:
      - npm run test

  build:
    commands:
      - cd ..
      - sam build
  
  post_build:
    commands:
      - sam package --s3-bucket $PACKAGE_BUCKET --output-template-file pkg-template.yml

artifacts:
  discard-paths: yes
  files:
    - pkg-template.yml