version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: 12
    commands:
      # Install sam cli
      - echo ${ROLE_ARN}

  pre_build:
    commands:
      - echo "This is a test"
  build:
    commands:
      - aws cloudformation package --template-file services/templates/app.yaml --s3-bucket "${SAM_BUCKET}" --output-template-file app-pkg-template.yml
