version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: 12
    commands:
      # Install sam cli
      - pip3 install --upgrade aws-sam-cli
      - sam --version
  pre_build:
    commands:
      - echo "This is a test"
  build:
    commands:
      - echo "Building artifacts"
